# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-prompt"
gem 'colorize', '~> 0.8.1'
gem 'json'
gem 'rspec'
gem 'tty-box'
gem 'tty-screen'
gem 'artii'
